name       : testdisk
version    : 7.0
release    : 3
source     :
    - https://www.cgsecurity.org/testdisk-7.0.tar.bz2 : 00bb3b6b22e6aba88580eeb887037aef026968c21a87b5f906c6652cbee3442d
license    : GPL-2.0
component  : system.utils
summary    : Testdisk Data Recovery
description: |
    TestDisk is powerful free data recovery software! It was primarily designed to help recover lost partitions and/or make non-booting disks bootable again when these symptoms are caused by faulty software, certain types of viruses or human error (such as accidentally deleting a Partition Table). Partition table recovery using TestDisk is really easy.
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libntfs-3g)
    - pkgconfig(QtGui)
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
