name       : testdisk
version    : '7.1'
release    : 6
source     :
    - https://www.cgsecurity.org/testdisk-7.1.tar.bz2 : 1413c47569e48c5b22653b943d48136cb228abcbd6f03da109c4df63382190fe
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://www.cgsecurity.org/wiki/TestDisk
summary    : Testdisk Data Recovery
description: |
    TestDisk is powerful free data recovery software! It was primarily designed to help recover lost partitions and/or make non-booting disks bootable again when these symptoms are caused by faulty software, certain types of viruses or human error (such as accidentally deleting a Partition Table). Partition table recovery using TestDisk is really easy.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(ext2fs)
    - pkgconfig(libjpeg)
    - pkgconfig(libntfs-3g)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
